//! Worked examples, generated by running them.
//!
//! **The examples are the strongest thing in the prompt, so they have
//! to be true.** Their user side used to be a `format!` in
//! `document.rs` that assembled a plausible-looking `# NEW EVENTS`
//! turn around the task text — the comment above it said "shaped like
//! a real one", which is the admission. A real user turn carries
//! `## RAN YOUR PROGRAM`, `### rows it added`, `### it printed` and
//! `## RIGHT NOW`; the imitation carried none of them, and all eight
//! examples stopped after the model's first reply, so nothing in the
//! prompt ever showed what comes *back*.
//!
//! That is not a cosmetic gap. Measured across nine live sessions on
//! 2026-09-24, deliberation about harness mechanics ran 2%–44% of
//! reasoning sentences, and the worst of them spent its budget
//! litigating one question — does `console.log` come back? — quoting
//! the card at itself, contradicting itself twice, and settling it
//! with "presumably". It had never seen a report.
//!
//! So the turns here are rendered by `document::render`, the same
//! function that renders the real thing. If it ever stops matching,
//! the snapshot test fails rather than the examples quietly drifting.

use crate::testkit::Conversation;
use crate::types::{Call, EventId, EventPayload, Exemplar};

/// One step of the worked session: what the person said, if anyone
/// spoke, the reply that followed, and what any question it asks is
/// answered with.
pub(crate) struct Step {
    /// The stem of the `.js` file holding the reply.
    pub stem: &'static str,
    /// What the person said before it, or `None` — most turns are the
    /// record talking, and a session where someone speaks every turn
    /// teaches a rhythm that does not exist.
    pub said: Option<&'static str>,
    /// Answers for the questions this reply raises, in the order they
    /// open: a `choose`, or one per helper it asks.
    pub answers: &'static [&'static str],
}

/// The session, in order. It is one afternoon on one repository, so a
/// reply can act on what the turn before it was shown — which is the
/// whole point and was impossible while each example stood alone.
///
/// **It ends on a reply, not on a report.** The conversation's own
/// first turn is a report like any other, so it continues the
/// alternation with no special case — and a person's words are one row
/// inside it rather than a turn of their own, which is why no seam is
/// needed between the last example and the real thing.
pub(crate) const SERIES: &[Step] = &[
    Step {
        stem: "01-finish",
        said: Some("the old hostname is still in the config — sort it out"),
        answers: &[],
    },
    Step {
        stem: "02-continue",
        said: Some("which files still mention the old hostname?"),
        answers: &[],
    },
    // No one speaks: the reply before it noted what it found, and this
    // one acts on it. The turn that carries no message at all is the
    // commonest turn there is and no example used to show one.
    Step {
        stem: "04-many",
        said: None,
        answers: &[],
    },
    Step {
        stem: "03-ask",
        said: Some("this setting looks stale — can you sort it out?"),
        answers: &["A"],
    },
    Step {
        stem: "05-keep",
        said: Some("why is CHECK failing?"),
        answers: &[],
    },
    // The reply that reads what the one before it kept, and acts.
    Step {
        stem: "09-act",
        said: None,
        answers: &[],
    },
    Step {
        stem: "06-fork",
        said: Some("three services started timing out last night — what do they have in common?"),
        answers: &["svc-b shipped at 23:40", "all three cap the pool at 8"],
    },
    Step {
        stem: "08-watch",
        said: Some("keep an eye on the migration job and tell me when it settles"),
        answers: &[],
    },
    Step {
        stem: "07-supervise",
        said: Some("run the integration suite for every package and tell me which ones fail"),
        answers: &[
            "nothing failed",
            "2 failed: timeout in pool_test",
            "nothing failed",
        ],
    },
];

/// Placeholder-shaped answers, in the real registry's result shapes.
///
/// **The tokens stay in capitals on purpose.** A live run on
/// 2026-09-17 copied an example's literals into a repository that had
/// none of them, which is why the examples say `PATH` and `OLD` rather
/// than something that looks like a real path. Executing them must not
/// undo that, so the *answers* are shaped to the placeholders rather
/// than the placeholders made concrete to suit the answers.
pub(crate) fn script(c: &mut Conversation) {
    c.tool("bash", |a| {
        let cmd = a.get(0).and_then(|v| v.as_str()).unwrap_or("");
        Ok(if cmd.starts_with("grep") {
            serde_json::json!({ "status": 0, "stdout": "PATH\nsrc/one.rs\n", "stderr": "" })
        } else if cmd.starts_with("ls") {
            serde_json::json!({ "status": 0, "stdout": "one\ntwo\nthree\n", "stderr": "" })
        } else {
            // A dummy stand-in for the real check, and it says so: what
            // matters to the example is the status and that something
            // came back, never the text.
            serde_json::json!({
                "status": 0,
                "stdout": "CHECK: dummy check — nothing real ran\nwants retries >= 5\n",
                "stderr": ""
            })
        })
    });
    c.tool("read_file", |a| {
        let path = a.get(0).and_then(|v| v.as_str()).unwrap_or("");
        Ok(if path.ends_with(".json") {
            serde_json::json!({ "content": "{ \"retries\": 3 }\n", "version": "v1" })
        } else {
            serde_json::json!({ "content": "// one\nOLD\nfn thing() {}\n", "version": "v1" })
        })
    });
    c.tool("replace_file", |_| {
        Ok(serde_json::json!({ "version": "v2", "diff": "@@ -2 +2 @@\n-OLD\n+NEW" }))
    });
    // A wait that does not wait. The source keeps its honest interval —
    // the example is teaching a cadence — and nothing leaks, because a
    // call that delivers nothing earns no row.
    c.answers("wait_until", serde_json::Value::Null);
}

/// Fill in a row id the example has to name literally.
///
/// **A reply that acts on what it was shown has to name the row it was
/// shown**, and the id is only knowable once the session has run —
/// which is the whole argument for generating these rather than
/// writing them. So the source carries a token in capitals, like every
/// other blank in these files, and it is replaced with the real id
/// before the reply is run. The rendered example therefore names an id
/// that genuinely refers to the row above it.
fn resolve_rows(js: &str, c: &Conversation) -> String {
    let mut out = js.to_owned();
    if let Some(row) = last_call_on(c, "read_file", ".json") {
        out = out.replace("CONF_ROW", &row.as_u64().to_string());
    }
    out
}

/// The id of the most recent call to `name` whose first argument ends
/// with `suffix`.
fn last_call_on(c: &Conversation, name: &str, suffix: &str) -> Option<EventId> {
    let mut hits: Vec<EventId> = c
        .tree()
        .events
        .values()
        .filter(|e| match &e.payload {
            EventPayload::Call(Call::Invoke { name: n, args, .. }) => {
                n == name
                    && args
                        .as_array()
                        .and_then(|a| a.first())
                        .and_then(|v| v.as_str())
                        .is_some_and(|p| p.ends_with(suffix))
            }
            _ => false,
        })
        .map(|e| e.id)
        .collect();
    hits.sort_by_key(|id| id.as_u64());
    hits.pop()
}

/// The oldest question this branch has asked and not been answered.
fn unanswered_ask(c: &Conversation) -> Option<EventId> {
    let tree = c.tree();
    let settled: std::collections::HashSet<EventId> = tree
        .events
        .values()
        .filter_map(|e| match &e.payload {
            EventPayload::Result { call, .. } => Some(*call),
            _ => None,
        })
        .collect();
    let mut asks: Vec<EventId> = tree
        .events
        .values()
        .filter(|e| {
            matches!(
                &e.payload,
                EventPayload::Call(Call::Send {
                    expects_reply: true,
                    ..
                })
            ) && !settled.contains(&e.id)
        })
        .map(|e| e.id)
        .collect();
    asks.sort_by_key(|id| id.as_u64());
    asks.into_iter().next()
}

/// Run the series and hand back the rendered turns, paired.
pub(crate) fn generate(js_of: impl Fn(&str) -> String) -> Vec<Exemplar> {
    let mut c = Conversation::for_exemplar_generation(
        "You are a capable general-purpose agent. Solve the user's task.",
        &crate::card::active().text.clone(),
    );
    script(&mut c);
    let mut out = Vec::new();
    for step in SERIES {
        if let Some(said) = step.said {
            c.user_says(said);
        }
        // **Captured now, not at the end.** A `peek` renders in the
        // ephemeral tail of exactly one request and is gone from the
        // next, so a document rendered once the session is over has
        // none of them — and `05-keep`, whose whole subject is what
        // `peek` puts in front of you, would have shown a row with
        // nothing under it. Each user turn is taken at the moment it
        // would have been sent.
        let user = last_user_turn(&c);
        let js = resolve_rows(&js_of(step.stem), &c);
        // **The resolved source is what ships.** `embedded()` reads
        // these `.js` files for the assistant side, so a file left
        // holding `CONF_ROW` would put that token in front of the
        // model. The generator owns the substitution and writes it
        // back, which also keeps the id in the reply and the id in the
        // report above it from ever disagreeing.
        if js != js_of(step.stem) {
            std::fs::write(format!("card/exemplars/{}.js", step.stem), &js).expect("write");
        }
        c.reply(&js);
        for reply in step.answers {
            let Some(open) = unanswered_ask(&c) else {
                break;
            };
            c.answer(open, serde_json::json!(reply));
        }
        out.push(Exemplar {
            user,
            assistant: assistant_turn(&c),
        });
    }
    out
}

/// The request as it stands: the last user message of the document the
/// next completion would carry, ephemeral tail included.
fn last_user_turn(c: &Conversation) -> String {
    let tail = c.runner().request_tail(c.tree()).unwrap_or_default();
    let doc = c.runner().document(c.tree(), 1 << 20).with_tail(&tail);
    doc.messages
        .iter()
        .rev()
        .find(|m| m.role == crate::document::ChatRole::User)
        .map(|m| without_a_readout_of_someone_elses_budget(&m.content))
        .unwrap_or_default()
}

/// Drop the fullness line from a captured turn.
///
/// **An example must not state a number about the reader's own
/// budget.** `## RIGHT NOW` carries live session state, and most of it
/// reads as shape — "17 rows, #6–#69" is obviously that session's.
/// The fullness line is not shape: it is a measurement of how much
/// room *you* have left, and frozen into a worked example it is a
/// measurement of somebody else's.
///
/// It shipped. `07-supervise` carried "51% full: 33443 bytes of 65536"
/// into every prompt — and doubly wrong, because the generator runs
/// with no model configured, so `context_tokens` was `None` and the
/// measurement fell back to bytes. A live session against a model with
/// a known window measures tokens against that window: the
/// same conversation reads "31360 tokens of 131072". So the number was
/// false, the unit was false, and the limit was false.
fn without_a_readout_of_someone_elses_budget(turn: &str) -> String {
    turn.lines()
        .filter(|l| !l.contains("% full:"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// The reply just logged, as the document renders it — annotations and
/// all, which is how the model's own turns come back to it.
fn assistant_turn(c: &Conversation) -> String {
    let doc = c.runner().document(c.tree(), 1 << 20);
    doc.messages
        .iter()
        .rev()
        .find(|m| m.role == crate::document::ChatRole::Assistant)
        .map(|m| m.content.clone())
        .unwrap_or_default()
}

/// Run the series against the shipped `.js` replies.
pub(crate) fn from_shipped() -> Vec<Exemplar> {
    generate(|stem| {
        std::fs::read_to_string(format!("card/exemplars/{stem}.js"))
            .unwrap_or_else(|e| panic!("card/exemplars/{stem}.js: {e}"))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// **The turns the model reads are the turns the renderer
    /// produces.** This is the whole point of generating them: if
    /// `document.rs` changes what a report looks like, the examples
    /// change with it or this fails. They used to be a `format!` that
    /// imitated a report and could drift from it silently — and did,
    /// for as long as reports have had sections.
    ///
    /// Run with `UPDATE_EXEMPLARS=1` to re-record.
    #[test]
    fn the_worked_examples_are_what_the_renderer_produces() {
        let made = from_shipped();
        assert_eq!(made.len(), SERIES.len(), "one exemplar per step");

        let update = std::env::var("UPDATE_EXEMPLARS").is_ok();
        let mut stale = Vec::new();
        for (step, ex) in SERIES.iter().zip(&made) {
            // `.txt` is the report that arrived; `.turn` is the reply
            // as the document renders it back — annotations and all,
            // which is how the model's own turns reach it and how no
            // worked example used to look.
            for (ext, made) in [("txt", &ex.user), ("turn", &ex.assistant)] {
                let path = format!("card/exemplars/{}.{ext}", step.stem);
                if std::fs::read_to_string(&path).unwrap_or_default() == *made {
                    continue;
                }
                if update {
                    std::fs::write(&path, made).expect("write");
                } else {
                    stale.push(step.stem);
                }
            }
        }
        assert!(
            stale.is_empty(),
            "these worked examples no longer match what the renderer produces: {stale:?}\n\
             re-record with `UPDATE_EXEMPLARS=1 cargo test -p agent \
             the_worked_examples_are_what_the_renderer_produces`"
        );
    }

    /// **The shipped order is the order they were run in.** They are
    /// one session, so `09-act` fetches a row `05-keep` kept and
    /// `04-many` sweeps what `02-continue` found. Shipping them in
    /// writing order — which is what `embedded()` did for as long as
    /// they stood alone — would leave those replies naming rows that
    /// are not above them.
    #[test]
    fn the_shipped_examples_are_the_series_in_its_own_order() {
        let shipped: Vec<&str> = crate::card::embedded()
            .exemplars
            .iter()
            .map(|e| {
                SERIES
                    .iter()
                    .find(|s| {
                        std::fs::read_to_string(format!("card/exemplars/{}.txt", s.stem))
                            .is_ok_and(|t| t == e.user)
                    })
                    .map(|s| s.stem)
                    .unwrap_or("<not a generated turn>")
            })
            .collect();
        let want: Vec<&str> = SERIES.iter().map(|s| s.stem).collect();
        assert_eq!(shipped, want, "shipped order must match the series");
    }

    /// **No example states how full anyone is.** `07-supervise`
    /// shipped "51% full: 33443 bytes of 65536" — a number about a
    /// session that is not the reader's, in the strongest position in
    /// the prompt. It was wrong three ways over: the generator runs
    /// with no model configured, so the measurement fell back to bytes
    /// against the byte budget, where a live session against a known
    /// window reports tokens against that window — the same
    /// conversation reads "31360 tokens of 131072".
    #[test]
    fn no_worked_example_reports_a_fullness() {
        for ex in &from_shipped() {
            assert!(
                !ex.user.contains("% full:"),
                "an example states a budget that is not the reader's: {}",
                ex.user
            );
        }
    }

    /// **The snapshot has to contain the things it exists to pin.**
    ///
    /// A comparison against a committed file passes just as happily
    /// when both sides are empty, and this session has already found a
    /// vocabulary guard reading 4% of its file and a conformance gate
    /// green on none of its 53,658. So the examples are asserted to
    /// carry the sections a report has — the ones no example carried
    /// before any of this, and the reason a live run spent 44% of its
    /// reasoning asking whether `console.log` comes back.
    #[test]
    fn the_examples_show_what_comes_back() {
        let made = from_shipped();
        let all = made
            .iter()
            .map(|e| e.user.as_str())
            .collect::<Vec<_>>()
            .join("\n");

        for section in [
            "## RAN YOUR PROGRAM",
            "### rows it added",
            "### it printed",
            "## RIGHT NOW",
            "### peeked — here for this reply only",
            "## MESSAGES",
            "noted:",
            "you told user:",
        ] {
            assert!(
                all.contains(section),
                "no worked example shows {section:?} — the half of the loop the model \
                 cannot otherwise see"
            );
        }

        // A reply that names a row it was shown, which is the thing a
        // single-turn example can never demonstrate.
        let act = &made[SERIES
            .iter()
            .position(|s| s.stem == "09-act")
            .expect("09-act")];
        assert!(
            act.user.contains("read_file(\"CONF.json\")"),
            "the turn before it was shown that row: {}",
            act.user
        );

        // Every program ran. The last step's report is never captured —
        // the series ends on a reply — so a trap there would otherwise
        // be invisible.
        assert_eq!(
            made.iter()
                .filter(|e| e.user.contains("It completed."))
                .count(),
            SERIES.len() - 1,
            "every reply but the last is reported as having completed"
        );
        assert!(
            !all.contains("uncaught") && !all.contains("is not defined"),
            "no worked example is a program that broke"
        );
    }
}

#[cfg(test)]
mod owes_probe {
    use crate::testkit::Conversation;

    #[test]
    fn does_a_completed_program_get_another_turn() {
        let mut c = Conversation::new();
        c.answers("bash", serde_json::json!({ "status": 0, "stdout": "x\n" }));
        c.user_says("do the thing");
        c.reply("```js\nawait tools.bash(\"x\");\n```\n");
        println!(
            "PROBE after a completed program, no finish: status={:?}",
            c.status()
        );
        let mut c2 = Conversation::new();
        c2.user_says("do the thing");
        c2.reply("just some prose, no block\n");
        println!(
            "PROBE after a prose-only reply:            status={:?}",
            c2.status()
        );
    }
}
